mvcproject/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class CourseController : Controller
{
    private readonly ICourseRepository _courseRepository;
    public CourseController(ICourseRepository courseRepository) => _courseRepository = courseRepository;
    [HttpGet]
    public async Task<IActionResult> GetCourse()
    {
        var all = await _courseRepository.GetCourseAllAsync();
        return View("CourseCard", all);
    }

    public async Task<IActionResult> AddCourse(CourseDto courseDto)
    {
        var course = new Course();
        course.Description = courseDto.Description;
        course.Name = courseDto.Name;
        course.Price = courseDto.Price;
        course.Url = courseDto.Url;
        await  _courseRepository.CreateCourseAsync(course);
        var all = await _courseRepository.GetCourseAllAsync();
        return View("CourseCard", all);
    }

    public async Task<IActionResult> UpdateCourse(int id, CourseDto courseDto)
    {
        if (!ModelState.IsValid) return View("CourseCard");

        var course = new CourseDto();

        course.Description = courseDto.Description;
        course.Name = courseDto.Name;
        course.Price = courseDto.Price;
        course.Url = courseDto.Url;

        await _courseRepository.UpdateCourseAsync(id,course);
        var all = await _courseRepository.GetCourseAllAsync();
        return View("CourseCard", all);

    }

    public async Task<IActionResult> DeleteCourse(int id)
    {
        if (!ModelState.IsValid) return View("CourseCard");

       await _courseRepository.DeleteCourseAsync(id);
        var all = await _courseRepository.GetCourseAllAsync();
        return View("CourseCard", all);
    }

    public async Task<IActionResult> GetById(int id)
    {
        if (!ModelState.IsValid) return View("CourseCard");

        var alsdsl = await _courseRepository.GetCourseByIdAsync(id);
        return View("UpdateCourse", alsdsl);

    }
}

mvcproject/Controllers/FeedBackController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvcproject.Data;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Model;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class FeedBackController : Controller
{
   private readonly AppDbContext _context;
   public IFeedbackRepository _feedbackRepository;

   public FeedBackController(AppDbContext context, IFeedbackRepository feedbackRepository)
   {
       _context = context;
       _feedbackRepository = feedbackRepository;
   }

   public async Task<IActionResult> Addfeedback(AddFeedBack feedBack)
   {
       var list = new Feedback();
       var first = await _context.User.FirstOrDefaultAsync(i => i.Id == feedBack.User_id);
       if (first != null)
       {
           list.User = first;
       }
       list.Name = feedBack.Name;
       list.Date = feedBack.Date;
       list.Phone_Number = feedBack.Phone_Number;
       var firstCourse = await _context.Course.FirstOrDefaultAsync(i => i.Id == feedBack.User_id);
       if (first != null)
       {
           list.Course = firstCourse;
       }

       await _feedbackRepository.CreateFeedback(list);
       var all = await _feedbackRepository.GetAllFeetback();
       return View("FeedbackTable", all);
   }


   public async Task<IActionResult> GetFeedback()
   {
       var all = await _feedbackRepository.GetAllFeetback();
       return View("FeedbackTable", all);
   }

   public async Task<IActionResult> Deletefeedback(int id)
   {
       if(!ModelState.IsValid) return View("FeedbackTable");

       await _feedbackRepository.DeleteFeedback(id);
       var all = await _feedbackRepository.GetAllFeetback();
       return View("FeedbackTable", all);
    }

   public async Task<IActionResult> GetById(int id)
   {
       if(!ModelState.IsValid) return View("FeedbackTable");
        
       var list = await _feedbackRepository.GetFeedbackById(id);
       return View("FeedBackUpdate", list);
    }
}

mvcproject/Controllers/ResultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvcproject.Data;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Model;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class ResultController : Controller
{
    private readonly AppDbContext _context;
    private readonly IResultRepository _resultRepository;

    public ResultController(AppDbContext context, IResultRepository resultRepository)
    {
        _resultRepository = resultRepository;
        _context = context;
    }

    public async Task<IActionResult> GetResult()
    {
        var all = await _resultRepository.GetAllResults();
        return View("ResultTable", all);
    }

    public async Task<IActionResult> GetById(int id)
    {
        var all = await _resultRepository.GetResultById(id);
        return View("ResultUpdate", all);
    }

    public async Task<IActionResult> AddResult(AddResult addResult)
    {
        var list = new Result();
        list.Url = addResult.Url;
        list.Name = addResult.Name;
        var first = await _context.Education.FirstOrDefaultAsync(i => i.Id == addResult.EducationId);
        if (first != null)
        {
            list.Education = first;
        }
        else throw new BadHttpRequestException("Not Found");


        var firstUser = await _context.User.FirstOrDefaultAsync(i => i.Id == addResult.UserId);
        if (firstUser != null)
        {
            list.User = firstUser;
        }
        else throw new BadHttpRequestException("Not Found");


        await _resultRepository.CreateResult(list);
        var all = await _resultRepository.GetAllResults();
        return View("ResultTable", all);
    }

    public async Task<IActionResult> UpdateResult(int id, AddResult addResult)
    {
        var list = new ResultDto();
        list.Url = addResult.Url;
        list.Name = addResult.Name;
        var first = await _context.Education.FirstOrDefaultAsync(i => i.Id == addResult.EducationId);
        if (first != null)
        {
            list.Education = first;
        }
        else throw new BadHttpRequestException("Not Found");
        var firstUser = await _context.User.FirstOrDefaultAsync(i => i.Id == addResult.UserId);
        if (firstUser != null)
        {
            list.User = firstUser;
        }
        else throw new BadHttpRequestException("Not Found");



        await _resultRepository.UpdateResult(id , list);
        var all = await _resultRepository.GetAllResults();
        return View("ResultTable", all);
    }

    public async Task<IActionResult> DeleteResult(int id)
    {
        if (!ModelState.IsValid) return View("ResultTable");

        await _resultRepository.DeleteResultById(id);
        var all = await _resultRepository.GetAllResults();
        return View("ResultTable", all);
    }
}

mvcproject/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class UserController : Controller
{
    private readonly IUserRepository _userrepository;
    private readonly IFeedbackRepository _feedbackRepository;
    private readonly IResultRepository _resultRepository;
    public UserController(IUserRepository userrepository, IFeedbackRepository feedbackRepository, IResultRepository resultRepository)
    {
        _userrepository = userrepository;
        _feedbackRepository = feedbackRepository;
        _resultRepository = resultRepository;
    }

    [HttpGet]
    public async Task<IActionResult> GetUsers()
    
    {
        var all = await _userrepository.GetAllUsers();
        return View("UserTable", all);
    }

    public async Task<IActionResult> AddUser(UserDto userDto)
    {
        if(!ModelState.IsValid) return View("UserTable");

        var user = new User();
        user.Email = userDto.Email;
        user.FullName = userDto.FullName;
        user.Password = userDto.Password;

        await _userrepository.CreateUsers(user);
        var all = await _userrepository.GetAllUsers();
        return View("UserTable", all);
    }

    public async Task<IActionResult> GetById(int id)
    {
        if (!ModelState.IsValid) return View("UserTable");

            var user =  await _userrepository.GetById(id);
            return View("UpdateUser", user);

    }

    public async Task<IActionResult> DeleteUser(int id)
    {
        if(!ModelState.IsValid) return View("UserTable");

        await _userrepository.DeleteUsers(id);
        var all = await _userrepository.GetAllUsers();
        return View("UserTable", all);
    }

    public async Task<IActionResult> UpdateUser()
    {
        return View("UpdateUser");
    }
    public async Task<IActionResult> UpdateUser(int id, UserDto userDto)
    {
        if (!ModelState.IsValid) return View("UserTable");

        var user = new UserDto();
        user.Email = userDto.Email;
        user.FullName = userDto.FullName;
        user.Password = userDto.Password;

        await _userrepository.UpdateUsers(id, user);
        var all = await _userrepository.GetAllUsers();
        return View("UserTable", all);

    }


    public async Task<IActionResult> UserCourse(int id)
    {
        if (!ModelState.IsValid) return View("UserTable");
        var all = await _userrepository.GetUserCourse(id);
        return View("UserCourse", all);
    }

    public async Task<IActionResult> UserFeedback(int id)
    {
        if (!ModelState.IsValid) return View("UserTable");
        var all = await _feedbackRepository.GetUserFeedback(id);
        return View("UserFeedback", all);
    }  
    
    public async Task<IActionResult> UserResult(int id)
    {
        if (!ModelState.IsValid) return View("UserTable");
        var all = await _resultRepository.GetUserResult(id);
        return View("UserResult", all);
    }
}

mvcproject/Views/User/UpdateUser.cshtml
@model mvcproject.Enitiy.User

<head>

</head>

<div style="width: 600px; height:fit-content; margin:auto; background: #0c1e35 ; box-shadow: 0 0 5px black; border-radius: 20px; padding: 100px;">
    <form asp-action="UpdateUser" asp-controller="User">
        <input name="id" value="@Model.Id" type="hidden"/>
        <input name="email" value="@Model.Email" type="email" class="form-control mt-3" placeholder="Email" />
        <input class="form-control mt-3" name="fullname" value="@Model.FullName" placeholder="Name" />
        <input class="form-control mt-3" name="password" value="@Model.Password" placeholder="Password" />
        <div class="d-flex justify-content-between align-items-center">
            <button asp-action="UpdateUser" asp-controller="User" class="btn btn-outline-warning mt-4">Update User</button>
        </div>
    </form>
    <form action="@Url.Action("GetUsers", "User")">
        <button asp-action="GetUsers" asp-controller="User" type="submit" class="btn btn-outline-primary mt-4">Cancel</button>
    </form>
</div>
    
    

mvcproject/Views/User/UserCourse.cshtml
@model List<mvcproject.Dto.CourseDto>

<head>

</head>
<div>
    <div class="d-flex justify-content-center position-absolute top-0 align-items-center end-0" style="height: 70px; box-shadow: 0 0 3px grey; left: 300px;">
        <form action="@Url.Action("GetUsers", "User")">
            <button asp-action="GetUsers" asp-controller="User" class="btn btn-outline-primary">Cancel</button>
        </form>
    </div>
    <div class="row">
        @foreach (var iteam in Model)
        {
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="@iteam.Url" class="card-img-top" alt="">
                    <div class="card-body">
                        <h5 class="card-title">@iteam.Id @iteam.Name</h5>
                        <p class="card-text">@iteam.Description</p>
                        <p class="card-text fw-bold">Price : @iteam.Price $</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <form action="@Url.Action("GetById", "Course")">
                                <input type="hidden" value="@iteam.Id" name="id"/>
                                <button class="btn btn-outline-success" asp-action="GetById" asp-controller="Course">Edit Course</button>
                            </form>
                            <form action="@Url.Action("DeleteCourse", "Course")">
                                <input type="hidden" value="@iteam.Id" name="id"/>
                                <button class="btn btn-outline-danger" asp-action="DeleteCourse" asp-controller="Course">Delete Course</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

mvcproject/Views/User/UserFeedback.cshtml
@model List<mvcproject.Dto.FeedbackDto>




<div class="d-flex justify-content-center position-absolute top-0 align-items-center end-0" style="height: 70px; box-shadow: 0 0 3px grey; left: 300px;">
    <form action="@Url.Action("GetUsers", "User")">
        <button asp-action="GetUsers" asp-controller="User" class="btn btn-outline-primary">Cancel</button>
    </form>
</div>







<head>
    <style>
        .table {
            border;
            1px solid #0c1e35;
            border-radius: 20px;
        }
    </style>
</head>
<div>

    <table class="table" style="overflow: scroll;">
        <thead>
            <tr>
                <td style="width: 100px">Id</td>
                <td style="width: 100px">Date</td>
                <td style="width: 300px">Name</td>
                <td style="width: 300px">Phone Number</td>
                <td style="width: 250px">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Feedback</h1>

                    </button>

                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <form action="@Url.Action("Addfeedback", "FeedBack")">
                                <div class="modal-content " style="width: 500px;">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add FeedBack</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <input name="name" type="text" class="form-control w-100 my-3" required placeholder="Name" />
                                        <input name="date" type="date" class="form-control w-100 my-3" required placeholder="Date" />
                                        <input name="Phone_Number" type="text" class="form-control w-100 my-3" required placeholder="Phone Number" />
                                        <input type="number" name="Course_id" class="form-control w-100 my-3" required placeholder="Course Id" />
                                        <input type="number" name="User_id" class="form-control w-100 my-3" required placeholder="User Id" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button asp-action="Addfeedback" asp-controller="FeedBack" type="submit" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var iteam in Model)
            {
                <tr>
                    <th><input style="width: 60px !;" readonly value="@iteam.Id" class="form-control w-100" /></th>
                    <th><input readonly style="width: 108px;" value="@iteam.Date" class="form-control" /></th>

                    <th>
                        <div readonly value="@iteam.Name" class="form-control" style="width: 200px; overflow:auto;">
                            @iteam.Name
                        </div>

                    </th>

                    <th>
                        <div readonly value="@iteam." class="form-control" style="width: 200px; overflow:auto;">
                            @iteam.Phone_Number
                        </div>

                    </th>

                    <th>
                        <form action="@Url.Action("Deletefeedback", "FeedBack")"><input type="hidden" name="id" value="@iteam.Id" /> <button class="btn btn-outline-danger" asp-action="Deletefeedback" asp-controller="FeedBack">Delete Feedback</button></form>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>

mvcproject/Views/User/UserResult.cshtml
@model List<mvcproject.Dto.ResultDto>

<div class="d-flex justify-content-center position-absolute top-0 align-items-center end-0" style="height: 70px; box-shadow: 0 0 3px grey; left: 300px;">
    <form action="@Url.Action("GetUsers", "User")">
        <button asp-action="GetUsers" asp-controller="User" class="btn btn-outline-primary">Cancel</button>
    </form>
</div>




<head>
    <style>
        .table {
            border;
            1px solid #0c1e35;
            border-radius: 20px;
        }
    </style>
</head>
<div>

    <table class="table" style="overflow: scroll;">
        <thead>
            <tr>
                <td style="width: 100px">Id</td>
                <td style="width: 100px">Name</td>
                <td style="width: 300px">Image</td>
                <td style="width: 250px">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Result</h1>

                    </button>

                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <form action="@Url.Action("AddResult", "Result")">
                                <div class="modal-content " style="width: 500px;">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Result</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <input name="name" type="text" class="form-control w-100 my-3" required placeholder="Name" />
                                        <input name="url" class="form-control w-100 my-3" required placeholder="Image" />
                                        <input type="number" name="EducationId" class="form-control w-100 my-3" required placeholder="Education Id" />
                                        <input type="number" name="UserId" class="form-control w-100 my-3" required placeholder="User Id" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button asp-action="AddResult" asp-controller="Result" type="submit" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var iteam in Model)
            {
                <tr>
                    <th><input style="width: 60px !;" readonly value="@iteam.ID" class="form-control w-100" /></th>
                    <th><input readonly style="width: 108px;" value="@iteam.Name" class="form-control" /></th>

                    <th>
                        <div readonly value="@iteam.Name" class="form-control" style="width: 200px; overflow:auto;">
                            @iteam.Name
                        </div>

                    </th>

                    <th>
                        <img readonly style="width: 200px; object-fit: contain;" src="@iteam.Url" value="@iteam.Url" class="form-control w-100" />
                    </th>
                    <th>
                        <form action="@Url.Action("GetByid", "Result")"><input type="hidden" name="id" value="@iteam.ID" /><button asp-action="GetByid" asp-controller="Result" type="submit" class="btn btn-outline-success my-3">Edit</button></form>
                        <form action="@Url.Action("DeleteResult", "Result")"><input type="hidden" name="id" value="@iteam.ID" /> <button class="btn btn-outline-danger" asp-action="DeleteResult" asp-controller="Result">Delete Home Work</button></form>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>

mvcproject/Views/User/UserTable.cshtml
@model List<mvcproject.Dto.UserDto>


<head>
    <style>
        .table{
            border;
            1px solid #0c1e35;
         
            border-radius: 20px;
        }
    </style>
</head>

<div>
    <div class="d-flex justify-content-center position-absolute top-0 align-items-center end-0" style="height: 100px; box-shadow: 0 0 3px grey; left: 300px;">
        <div class="w-25">
            <form action="@Url.Action("UserCourse", "User")">
                <button style="margin-top: 22px;" asp-action="UserCourse" asp-controller="User" class="btn btn-outline-primary">User Course</button>
                <input name="id" class="form-control w-25 my-3" type="number" /> 
            </form>
        </div>
        <div class="w-25">
            <form action="@Url.Action("UserFeedback", "User")">
                <button style="margin-top: 22px;" asp-action="UserFeedback" asp-controller="User" class="btn btn-outline-primary">User Feedback</button>
                <input name="id" class="form-control w-25 my-3" type="number" />

            </form>
        </div>
        <div class="w-25">
            <form action="@Url.Action("UserResult", "User")">
                <button style="margin-top: 22px;" asp-action="UserResult" asp-controller="User" class="btn btn-outline-primary">User Result</button>
                <input name="id" class="form-control w-25 my-3" type="number" />

            </form>
        </div>
    </div>

    <table class="table" style="overflow: scroll;">
        <thead>
        <tr>
            <td style="width: 50px">Id</td>
            <td style="width: 300px">Name</td>
            <td style="width: 300px">Email</td>
            <td style="width: 300px">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Add User
                </button>

                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <form action="@Url.Action("AddUser", "User")">
                            <div class="modal-content " style="width: 500px;">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add User</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">

                                    <input name="fullname" class="form-control w-100 my-3" required placeholder="User Name"/>
                                    <input name="email" class="form-control w-100 my-3" required placeholder="Email"/>
                                    <input name="password" class="form-control w-100 my-3" required placeholder="Password"/>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <button asp-action="AddUser" asp-controller="User" type="submit" class="btn btn-primary">Save changes</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </td>
        </tr>
        </thead>
        @foreach (var iteam in Model)
        {
            <tr >
                <th><input readonly value="@iteam.Id" class="form-control w-100"/></th>
                <th><input readonly value="@iteam.FullName" class="form-control w-100"/></th>
                <th><input readonly value="@iteam.Email" class="form-control w-100"/></th>
                <th>
                    <form action="@Url.Action("GetById", "User")"><input type="hidden" name="id" value="@iteam.Id"/><button asp-action="GetById" asp-controller="User" type="submit" class="btn btn-outline-success my-3">Edit</button></form>
                    <form action="@Url.Action("DeleteUser", "User")"><input type="hidden" name="id" value="@iteam.Id"/> <button class="btn btn-outline-danger" asp-action="DeleteUser" asp-controller="User">Delete User</button></form>
                </th>
            </tr>
        }
        </tbody>
    </table>
</div>