mvcproject/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class CourseController : Controller
{
    private readonly ICourseRepository _courseRepository;
    public CourseController(ICourseRepository courseRepository) => _courseRepository = courseRepository;
    [HttpGet]
    public async Task<IActionResult> GetCourse()
    {
        var all = await _courseRepository.GetCourseAllAsync();
        return View("CourseCard", all);
    }

    public async Task<IActionResult> AddCourse(CourseDto courseDto)
    {
        var course = new Course();
        course.Description = courseDto.Description;
        course.Name = courseDto.Name;
        course.Price = courseDto.Price;
        course.Url = courseDto.Url;
        await  _courseRepository.CreateCourseAsync(course);
        var all = await _courseRepository.GetCourseAllAsync();
        return View("CourseCard", all);
    }

    public async Task<IActionResult> UpdateCourse(int id, CourseDto courseDto)
    {
        if (!ModelState.IsValid) return View("CourseCard");

        var course = new CourseDto();

        course.Description = courseDto.Description;
        course.Name = courseDto.Name;
        course.Price = courseDto.Price;
        course.Url = courseDto.Url;

        await _courseRepository.UpdateCourseAsync(id,course);
        var all = await _courseRepository.GetCourseAllAsync();
        return View("CourseCard", all);

    }

    public async Task<IActionResult> DeleteCourse(int id)
    {
        if (!ModelState.IsValid) return View("CourseCard");

       await _courseRepository.DeleteCourseAsync(id);
        var all = await _courseRepository.GetCourseAllAsync();
        return View("CourseCard", all);
    }

    public async Task<IActionResult> GetById(int id)
    {
        if (!ModelState.IsValid) return View("CourseCard");

        var alsdsl = await _courseRepository.GetCourseByIdAsync(id);
        return View("UpdateCourse", alsdsl);

    }
}

mvcproject/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvcproject.Data;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Model;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class TaskController : Controller
{
    private readonly AppDbContext _context;
    private readonly ITaskRepository _taskRepository;

    public TaskController(AppDbContext context, ITaskRepository taskRepository)
    {
        _context = context;
        _taskRepository = taskRepository;
    }
    public async Task<IActionResult> GetTask()
    {
        var all = await _taskRepository.GetAllTasks();
        return View("TaskTable", all);
    }

    public async Task<IActionResult> GetById(int id)
    {
        if (!ModelState.IsValid) return View("TaskTable");
        var all = await _taskRepository.GetTasksById(id);
        return View("Taskupdate", all);
    }

    public async Task<IActionResult> DeleteTask(int id)
    {
        if (!ModelState.IsValid) return View("TaskTable");

        await _taskRepository.DeleteTask(id);
        var all = await _taskRepository.GetAllTasks();
        return View("TaskTable", all);
    }

    public async Task<IActionResult> AddTask(AddTask addTask)
    {
        var list = new Enitiy.Task();
        list.Data = addTask.Data;
        list.Description = addTask.Description;
        list.Title = addTask.Title;
        list.complete = addTask.complete;
        var first = await _context.Lessons.FirstOrDefaultAsync(i => i.Id == addTask.LessonsId);
        if (first != null)
        {
            list.Lessons = first;
        }
        else throw new BadHttpRequestException("Not Found");


        await _taskRepository.CreateTask(list);
        var all = await _taskRepository.GetAllTasks();
        return View("TaskTable", all);
    }

    public async Task<IActionResult> UpdateTask(int id, AddTask addTask)
    {
        var list = new TaskDto();
        list.Data = addTask.Data;
        list.Description = addTask.Description;
        list.Title = addTask.Title;
        list.complete = addTask.complete;
        var first = await _context.Lessons.FirstOrDefaultAsync(i => i.Id == addTask.LessonsId);
        if (first != null)
        {
            list.Lessons = first;
        }
        else throw new BadHttpRequestException("Not Found");



        await _taskRepository.UpdateTask(id ,list); 
        var all = await _taskRepository.GetAllTasks();
        return View("TaskTable", all);
    }
}

mvcproject/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvcproject.Data;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Model;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class TestController : Controller
{
    private readonly AppDbContext _context;
    private readonly ITestRepository _testRepository;

    public TestController(AppDbContext context, ITestRepository testRepository)
    {
        _context = context;
        _testRepository = testRepository;
    }
    [HttpGet]
    public async Task<IActionResult> GetTest()
    {
        var all = await _testRepository.GetAllTest();
        return View("TestTable", all);
    }

    public async Task<IActionResult> GetById(int id)
    {
        if (!ModelState.IsValid) return View("TestTable");
        var all = await _testRepository.GetTestById(id);
        return View("TestTable");
    }

    public async Task<IActionResult> DeleteTets(int id)
    {
        if (!ModelState.IsValid) return View("TestTable");
        await _testRepository.DeleteTest(id);
        var all = await _testRepository.GetAllTest();
        return View("TestTable", all);
    }

    public async Task<IActionResult> AddTest(AddTests addTests)
    {
        var list = new Tests();
        list.Queshioquestion = addTests.Queshioquestion;
        list.correct = addTests.correct;
        list.incorrect = new List<string>();
        if (addTests.incorrect != null)
        {
                list.incorrect.AddRange(addTests.incorrect);
        }

        var first = await _context.Course.FirstOrDefaultAsync(i => i.Id == addTests.CourseId);
        if (first != null)
        {
            list.Course = first;
        }

        await _testRepository.CreateTest(list);
        var all = await _testRepository.GetAllTest();
        return View("TestTable", all);
    }

    public async Task<IActionResult> UpdateTest(int id, AddTests addTests)
    {
        var list = new TestsDto();
        list.Queshioquestion = addTests.Queshioquestion;
        list.correct = addTests.correct;
        list.incorrect = new List<string>();
        if (addTests.incorrect != null)
        {
            list.incorrect.AddRange(addTests.incorrect);
        }

        var first = await _context.Course.FirstOrDefaultAsync(i => i.Id == addTests.CourseId);
        if (first != null)
        {
            list.Course = first;
        }

        await _testRepository.UpdateTest(id , list);
        var all = await _testRepository.GetAllTest();
        return View("TestTable", all);
    }
}

mvcproject/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class UserController : Controller
{
    private readonly IUserRepository _userrepository;
    private readonly IFeedbackRepository _feedbackRepository;
    private readonly IResultRepository _resultRepository;
    public UserController(IUserRepository userrepository, IFeedbackRepository feedbackRepository, IResultRepository resultRepository)
    {
        _userrepository = userrepository;
        _feedbackRepository = feedbackRepository;
        _resultRepository = resultRepository;
    }

    [HttpGet]
    public async Task<IActionResult> GetUsers()
    
    {
        var all = await _userrepository.GetAllUsers();
        return View("UserTable", all);
    }

    public async Task<IActionResult> AddUser(UserDto userDto)
    {
        if(!ModelState.IsValid) return View("UserTable");

        var user = new User();
        user.Email = userDto.Email;
        user.FullName = userDto.FullName;
        user.Password = userDto.Password;

        await _userrepository.CreateUsers(user);
        var all = await _userrepository.GetAllUsers();
        return View("UserTable", all);
    }

    public async Task<IActionResult> GetById(int id)
    {
        if (!ModelState.IsValid) return View("UserTable");

            var user =  await _userrepository.GetById(id);
            return View("UpdateUser", user);

    }

    public async Task<IActionResult> DeleteUser(int id)
    {
        if(!ModelState.IsValid) return View("UserTable");

        await _userrepository.DeleteUsers(id);
        var all = await _userrepository.GetAllUsers();
        return View("UserTable", all);
    }

    public async Task<IActionResult> UpdateUser()
    {
        return View("UpdateUser");
    }
    public async Task<IActionResult> UpdateUser(int id, UserDto userDto)
    {
        if (!ModelState.IsValid) return View("UserTable");

        var user = new UserDto();
        user.Email = userDto.Email;
        user.FullName = userDto.FullName;
        user.Password = userDto.Password;

        await _userrepository.UpdateUsers(id, user);
        var all = await _userrepository.GetAllUsers();
        return View("UserTable", all);

    }


    public async Task<IActionResult> UserCourse(int id)
    {
        if (!ModelState.IsValid) return View("UserTable");
        var all = await _userrepository.GetUserCourse(id);
        return View("UserCourse", all);
    }

    public async Task<IActionResult> UserFeedback(int id)
    {
        if (!ModelState.IsValid) return View("UserTable");
        var all = await _feedbackRepository.GetUserFeedback(id);
        return View("UserFeedback", all);
    }  
    
    public async Task<IActionResult> UserResult(int id)
    {
        if (!ModelState.IsValid) return View("UserTable");
        var all = await _resultRepository.GetUserResult(id);
        return View("UserResult", all);
    }
}

mvcproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcproject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvcproject.styles.css" asp-append-version="true" />
</head>
<body>
<div class="d-flex">
    <div>
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Document</title>
                <link rel="stylesheet" href="./dfsdfd.css">

            </head>
            <body>
                <div class="layout" style="width: 300px; height: 600px;">
                    <aside id="sidebar" class="sidebar break-point-sm has-bg-image" style="height: 100vh;">
                        <a id="btn-collapse" class="sidebar-collapser"><i class="ri-arrow-left-s-line"></i></a>
                        <div class="image-wrapper">
                            <img src="assets/images/sidebar-bg.jpg" alt="sidebar background" />
                        </div>
                        <div class="sidebar-layout">
                            <div class="sidebar-header">
                                <div class="pro-sidebar-logo " style="width: 70px !important;">
                                    <div>MVC</div>
                                    <h5>Admin </h5>
                                </div>
                            </div>
                            <div class="sidebar-content">
                                <nav class="menu open-current-submenu">
                                    <ul>
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetUsers","User")">
                                            <a asp-action="GetUsers" asp-controller="User">
                                                <span class="menu-icon">
                                                    <i class="ri-book-2-fill"></i>
                                                </span>
                                                <span class="menu-title">User</span>
                                            </a>
                                            </form>
                                        </li>
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetCourse", "Course")">
                                            <a asp-controller="Course" asp-action="GetCourse">
                                                <span class="menu-icon">
                                                    <i class="ri-book-2-fill"></i>
                                                </span>
                                                <span class="menu-title">Course</span>
                                            </a>
                                            </form>
                                        </li>
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetEducation", "Education")">
                                                <a asp-action="GetEducation" asp-controller="Education">
                                                    <span class="menu-icon">
                                                        <i class="ri-book-2-fill"></i>
                                                    </span>
                                                    <span class="menu-title">Education</span>
                                                </a>
                                            </form>
                                
                                        </li>
                                        <li class="menu-item">
                                            <form action="@Url.Action("DeleeteLesson", "Lesson")">
                                                <a asp-action="GetLesson" asp-controller="Lesson">
                                                    <span class="menu-icon">
                                                        <i class="ri-book-2-fill"></i>
                                                    </span>
                                                    <span class="menu-title">Lesson</span>
                                                </a>
                                            </form>
                                        </li>
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetTask","Task")">
                                                <a asp-action="GetTask" asp-controller="Task">
                                                    <span class="menu-icon">
                                                        <i class="ri-book-2-fill"></i>
                                                    </span>
                                                    <span class="menu-title">Task</span>
                                                </a>
                                            </form>
                              
                                        </li>
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetHomeWork", "HomeWork")">
                                                <a asp-action="GetHomeWork" asp-controller="HomeWork">
                                                    <span class="menu-icon">
                                                        <i class="ri-book-2-fill"></i>
                                                    </span>
                                                    <span class="menu-title">Home Work</span>

                                                </a>
                                            </form>
                                     
                                        </li>
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetResult", "Result")">
                                                <a asp-controller="Result" asp-action="GetResult">
                                                    <span class="menu-icon">
                                                        <i class="ri-calendar-fill"></i>
                                                    </span>
                                                    <span class="menu-title">Result</span>
                                                </a>
                                            </form>
                                        </li>    
                                        
                                        <li class="menu-item">
                                            <form action="@Url.Action("Deletefeedback","FeedBack")">
                                                <a asp-controller="FeedBack" asp-action="GetFeedback">
                                                    <span class="menu-icon">
                                                        <i class="ri-calendar-fill"></i>
                                                    </span>
                                                    <span class="menu-title">FeedBack</span>
                                                </a>
                                            </form>
                                        </li>
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetReview","Review")">
                                                <a asp-controller="Review" asp-action="GetReview">
                                                    <span class="menu-icon">
                                                        <i class="fa-solid fa-house"></i>
                                                    </span>
                                                    <span class="menu-title">Review</span>
                                                </a>
                                            </form>

                                        </li>   
                                        
                                        
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetReacher", "Teacher")">
                                                <a asp-action="GetReacher" asp-controller="Teacher">
                                                    <span class="menu-icon">
                                                        <i class="fa-solid fa-house"></i>
                                                    </span>
                                                    <span class="menu-title">Teacher</span>
                                                </a>
                                            </form>
                                        </li>                               
                                        
                                        <li class="menu-item">
                                            <form action="@Url.Action("GetTest", "Test")">
                                                <a asp-controller="Test" asp-action="GetTest">
                                                    <span class="menu-icon">
                                                        <i class="fa-solid fa-house"></i>
                                                    </span>
                                                    <span class="menu-title">Test</span>
                                                </a>
                                            </form>
                                       
                                        </li>
                                    </ul>
                                </nav>
                            </div>

                        </div>
                </aside>
    </div>
</body>
<script src="https://kit.fontawesome.com/4a51ac7252.js" crossorigin="anonymous"></script>

</html>
    </div>
        <div role="main" style="padding: 0 0 150px 0; overflow-y:scroll; overflow-x:hidden;  margin: 100px auto ; width: 1100px; height: 700px;">
            @RenderBody()
    </div>
</div>
<div class="container">
    <main  class="pb-3">
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>