mvcproject/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvcproject.Data;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Model;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class ReviewController : Controller
{
    private readonly AppDbContext _context;
    private readonly IReviewRepository _reviewRepository;

    public ReviewController(AppDbContext context, IReviewRepository reviewRepository)
    {
        _context = context;
        _reviewRepository = reviewRepository;
    }

    public async Task<IActionResult> GetReview()
    {
        var all = await _reviewRepository.GetAllReviews();
        return View("Reviewtable", all);   
    }

    public async Task<IActionResult> GetById(int id)
    {
        var all = await _reviewRepository.GetReviewById(id);
        return View("ReviewUpdate", all);
    }

    public async Task<IActionResult> DeleteReview(int id)
    {
        if(!ModelState.IsValid) return View("Reviewtable");

        await _reviewRepository.DeleteReview(id);
        var all = await _reviewRepository.GetAllReviews();
        return View("Reviewtable", all);
    }

    public async Task<IActionResult> AddReview(AddReview addReview)
    {
        var list = new Review();
        list.Course_info = addReview.Course_info;
        list.Course_name = addReview.Course_name;
        list.comment = addReview.comment;

        var first = await _context.Task.FirstOrDefaultAsync(i => i.Id == addReview.TaskId);
        if (first != null)
        {
            list.Task = first;
        }

        await _reviewRepository.CreateReview(list);
        var all = await _reviewRepository.GetAllReviews();
        return View("Reviewtable", all);
    }


    public async Task<IActionResult> UpdateReview(int id, AddReview addReview)
    {
        var list = new ReviewDto();
        list.Course_info = addReview.Course_info;
        list.Course_name = addReview.Course_name;
        list.comment = addReview.comment;

        var first = await _context.Task.FirstOrDefaultAsync(i => i.Id == addReview.TaskId);
        if (first != null)
        {
            list.Task = first;
        }

        await _reviewRepository.UpdateReview(id ,list);
        var all = await _reviewRepository.GetAllReviews();
        return View("Reviewtable", all);
    }
}

mvcproject/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvcproject.Data;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Model;
using mvcproject.Repository;

namespace mvcproject.Controllers;

public class TaskController : Controller
{
    private readonly AppDbContext _context;
    private readonly ITaskRepository _taskRepository;

    public TaskController(AppDbContext context, ITaskRepository taskRepository)
    {
        _context = context;
        _taskRepository = taskRepository;
    }
    public async Task<IActionResult> GetTask()
    {
        var all = await _taskRepository.GetAllTasks();
        return View("TaskTable", all);
    }

    public async Task<IActionResult> GetById(int id)
    {
        if (!ModelState.IsValid) return View("TaskTable");
        var all = await _taskRepository.GetTasksById(id);
        return View("Taskupdate", all);
    }

    public async Task<IActionResult> DeleteTask(int id)
    {
        if (!ModelState.IsValid) return View("TaskTable");

        await _taskRepository.DeleteTask(id);
        var all = await _taskRepository.GetAllTasks();
        return View("TaskTable", all);
    }

    public async Task<IActionResult> AddTask(AddTask addTask)
    {
        var list = new Enitiy.Task();
        list.Data = addTask.Data;
        list.Description = addTask.Description;
        list.Title = addTask.Title;
        list.complete = addTask.complete;
        var first = await _context.Lessons.FirstOrDefaultAsync(i => i.Id == addTask.LessonsId);
        if (first != null)
        {
            list.Lessons = first;
        }
        else throw new BadHttpRequestException("Not Found");


        await _taskRepository.CreateTask(list);
        var all = await _taskRepository.GetAllTasks();
        return View("TaskTable", all);
    }

    public async Task<IActionResult> UpdateTask(int id, AddTask addTask)
    {
        var list = new TaskDto();
        list.Data = addTask.Data;
        list.Description = addTask.Description;
        list.Title = addTask.Title;
        list.complete = addTask.complete;
        var first = await _context.Lessons.FirstOrDefaultAsync(i => i.Id == addTask.LessonsId);
        if (first != null)
        {
            list.Lessons = first;
        }
        else throw new BadHttpRequestException("Not Found");



        await _taskRepository.UpdateTask(id ,list); 
        var all = await _taskRepository.GetAllTasks();
        return View("TaskTable", all);
    }
}

mvcproject/Views/Review/ReviewUpdate.cshtml
@model mvcproject.Enitiy.Review

<head>

</head>

<div style="width: 600px; height:fit-content; margin:auto; background: #0c1e35 ; box-shadow: 0 0 5px black; border-radius: 20px; padding: 100px;">
    <form asp-action="UpdateReview" asp-controller="Review">
        <input name="id" value="@Model.Id" type="hidden" />
        <input name="Course_info" value="@Model.Course_info"  class="form-control my-3" placeholder="Course info" />
        <input class="form-control my-3" name="Course_name" value="@Model.Course_name" placeholder="Course name" />
        <input name="comment"  class="form-control my-3" name="Title" value="@Model.comment" placeholder="Comment" />
        <input class="form-control my-3" name="TaskId" placeholder="Task Id" />
         

        <div class="d-flex justify-content-between align-items-center">
            <button asp-action="UpdateReview" asp-controller="Review" class="btn btn-outline-warning mt-4">Update Review</button>
        </div>
    </form>
    <form action="@Url.Action("GetTask", "Task")">
        <button asp-action="GetReview" asp-controller="Review" type="submit" class="btn btn-outline-primary mt-4">Cancel</button>
    </form>
</div>

mvcproject/Views/Review/Reviewtable.cshtml
@model List<mvcproject.Dto.ReviewDto>


<head>
    <style>
        .table {
            border;
            1px solid #0c1e35;
            border-radius: 20px;
        }
    </style>
</head>
<div>

    <table class="table" style="overflow: scroll;">
        <thead>
            <tr>
                <td style="width: 100px">Id</td>
                <td style="width: 100px">Comment</td>
                <td style="width: 300px">Course Info</td>
                <td style="width: 300px">Course Name</td>
                <td style="width: 250px">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Review</h1>

                    </button>

                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <form action="@Url.Action("AddReview", "Review")">
                                <div class="modal-content " style="width: 500px;">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Review</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <input name="comment" type="text" class="form-control w-100 my-3" required placeholder="Comment" />
                                        <input name="Course_info" class="form-control w-100 my-3" required placeholder="Course info" />
                                        <input name="Course_name" class="form-control w-100 my-3" required placeholder="Course name " />
                                        <input type="number" name="TaskId" class="form-control w-100 my-3" required placeholder="Task Id" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button asp-action="AddReview" asp-controller="Review" type="submit" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var iteam in Model)
            {
                <tr>
                    <th><input style="width: 60px !;" readonly value="@iteam.Id" class="form-control w-100" /></th>

                    <th>
                        <div readonly value="@iteam.comment" class="form-control" style="width: 200px; overflow:auto;">
                            @iteam.comment
                        </div>
                    </th> 
                    
                    <th>
                        <div readonly value="@iteam.Course_info" class="form-control" style="width: 200px; overflow:auto;">
                            @iteam.Course_info
                        </div>
                    </th>  
                    
                    <th>
                        <div readonly value="@iteam.Course_name" class="form-control" style="width: 200px; overflow:auto;">
                            @iteam.Course_name
                        </div>
                    </th>

                    <th>
                        <form action="@Url.Action("GetByid", "Review")"><input type="hidden" name="id" value="@iteam.Id" /><button asp-action="GetByid" asp-controller="Review" type="submit" class="btn btn-outline-success my-3">Edit</button></form>
                        <form action="@Url.Action("DeleteReview", "Review")"><input type="hidden" name="id" value="@iteam.Id" /> <button class="btn btn-outline-danger" asp-action="DeleteReview" asp-controller="Review">Delete Review</button></form>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>