mvcproject/Controllers/EducationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvcproject.Data;
using mvcproject.Dto;
using mvcproject.Enitiy;
using mvcproject.Model;
using mvcproject.Repository;
using System.Collections.Generic;

namespace mvcproject.Controllers;

public class EducationController : Controller
{
    private readonly IEducationRepository _educationRepository;
    private readonly AppDbContext _appDbContext;

    public EducationController(IEducationRepository educationRepository, AppDbContext appDbContext)
    {
        _educationRepository = educationRepository;
        _appDbContext = appDbContext;
    }
    [HttpGet]
    public async Task<IActionResult> GetEducation()
    {

        var list = await _educationRepository.GetAllEducation();
        return View("EducationTable", list);

    }

    public async Task<IActionResult> AddEducation(AddEducation educationDto)
    {
        var list = new Education();
        var findCourse = await _appDbContext.Course.FirstOrDefaultAsync(c => c.Id == educationDto.CourseID);
        if (findCourse != null)
        {
            list.course = findCourse;
          
        }



        list.Description = educationDto.Description;
        list.courseСompletion = new List<string>();

        if (educationDto.courseСompletion != null)
        {
            list.courseСompletion.AddRange(educationDto.courseСompletion);
        }
        list.Tranding = educationDto.Tranding;

        await _educationRepository.CreateEducation(list);
        var listAll = await _educationRepository.GetAllEducation();
        return View("EducationTable", listAll);
    }


    public async Task<IActionResult> GetByid(int id)
    {
        var list = await _educationRepository.GetEducationById(id);
        return View("EducationUpdate" , list);
    }

    public async Task<IActionResult> DeleteEducation(int id)
    {
        if(!ModelState.IsValid) return View("EducationTable");


         await _educationRepository.DeleteEducationById(id);
         var list = await _educationRepository.GetAllEducation();
        return View("EducationTable", list);

    }

    public async Task<IActionResult> UpdateEducation(int id , AddEducation educationDto)
    {
        if (!ModelState.IsValid) return View("EducationTable");

        var list = new EducationDto();
        var findCourse = await _appDbContext.Course.FirstOrDefaultAsync(c => c.Id == educationDto.CourseID);
        if (findCourse != null)
        {
            list.Course = findCourse;
        }
        list.Description = educationDto.Description;
        list.courseСompletion = new List<string>(educationDto.courseСompletion);
        list.Tranding = educationDto.Tranding;

        await _educationRepository.UpdateEducation(id, list);
        var listAll = await  _educationRepository.GetAllEducation();
        return View("EducationTable", listAll);
    }
}

mvcproject/Views/Education/EducationTable.cshtml
@model List<mvcproject.Dto.EducationDto>


<head>
    <style>
        .table {
            border;
            1px solid #0c1e35;
            border-radius: 20px;
        }
    </style>
</head>
<div>

    <table class="table" style="overflow: scroll;">
        <thead>
            <tr>
                <td style="width: 100px">Id</td>
                <td style="width: 300px">Title</td>
                <td style="width: 300px">Description</td>
                <td style="width: 300px">Completion</td>
                <td style="width: 300px">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">

                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Education</h1>

                    </button>

                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <form action="@Url.Action("AddEducation", "Education")">
                                <div class="modal-content " style="width: 500px;">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Education</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <input name="Tranding" class="form-control w-100 my-3" required placeholder="Title" />
                                        <input name="Description" class="form-control w-100 my-3" required placeholder="Description" />
                                        <input name="courseId" class="form-control w-100 my-3" required placeholder="Course Id" />
                                        <label for="options">Options:</label>
                                        <input name="courseСompletion[0]" class="form-control w-100 my-3" required placeholder="Complet Course" />
                                        <input name="courseСompletion[1]" class="form-control w-100 my-3" required placeholder="Complet Course Options 1" />
                                        <input name="courseСompletion[2]" class="form-control w-100 my-3" required placeholder="Complet Course Options 2" />
                                        <input name="courseСompletion[3]" class="form-control w-100 my-3" required placeholder="Complet Course Options 3" />
                                        <input name="courseСompletion[4]" class="form-control w-100 my-3" required placeholder="Complet Course Options 4" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button asp-action="AddEducation" asp-controller="Education" type="submit" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var iteam in Model)
            {
                <tr>
                    <th><input readonly value="@iteam.Id" class="form-control w-100" /></th>
                    <th><input readonly value="@iteam.Tranding" class="form-control w-100" /></th>
                    <th><div readonly value="@iteam.Description" class="form-control w-100">
                            @iteam.Description
                    </div></th>
                    <th><div readonly class="form-control">
                        @foreach (var i in iteam.courseСompletion)
                        {
                            <h6>@i</h6> <br/>
                        }
                    </div></th>
                    <th>
                        <form action="@Url.Action("GetByid", "Education")"><input type="hidden" name="id" value="@iteam.Id" /><button asp-action="GetByid" asp-controller="Education" type="submit" class="btn btn-outline-success my-3">Edit</button></form>
                        <form action="@Url.Action("DeleteEducation", "Education")"><input type="hidden" name="id" value="@iteam.Id" /> <button class="btn btn-outline-danger" asp-action="DeleteEducation" asp-controller="Education">Delete Education</button></form>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>

mvcproject/Views/Education/EducationUpdate.cshtml
@model mvcproject.Enitiy.Education

<head>

</head>

<div style="width: 600px; height:fit-content; margin:auto; background: #0c1e35 ; box-shadow: 0 0 5px black; border-radius: 20px; padding: 100px;">
    <form asp-action="UpdateEducation" asp-controller="Education">
        <input name="id" value="@Model.Id" type="hidden"/>
        <input name="Tranding" value="@Model.Tranding" type="text" class="form-control mt-3" placeholder="Title" />
        <input class="form-control mt-3" name="Description" value="@Model.Description" placeholder="Description" />
        <input class="form-control mt-3" name="courseСompletion" value="@Model.courseСompletion[0]" placeholder="Complet " />
        <input class="form-control mt-3" name="courseСompletion" value="@Model.courseСompletion[1]" placeholder="Complet " />
        <input class="form-control mt-3" name="courseСompletion" value="@Model.courseСompletion[2]" placeholder="Complet " />
        <input class="form-control mt-3" name="courseСompletion" value="@Model.courseСompletion[3]" placeholder="Complet " />
        <input class="form-control mt-3" name="courseСompletion" value="@Model.courseСompletion[4]" placeholder="Complet " />
        <div class="d-flex justify-content-between align-items-center">
            <button asp-action="UpdateEducation" asp-controller="Education" class="btn btn-outline-warning mt-4">Update Education</button>
        </div>
    </form>
    <form action="@Url.Action("GetEducation", "Education")">
        <button asp-action="GetEducation" asp-controller="Education" type="submit" class="btn btn-outline-primary mt-4">Cancel</button>
    </form>
</div>